-- PULSE — complete database schema
--
-- Generated by scripts/build-schema.mjs from database/migrations. Do not edit by hand:
-- edit the numbered migration and regenerate, so both stay in step.
--
-- Paste the whole file into the Supabase SQL editor and run it once.
-- It is safe to run again — every statement is guarded.

-- ─────────────────────────────────────────────────────────────────────────
-- 001_initial_schema.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT,
  avatar_url TEXT,
  investment_experience VARCHAR(50),
  risk_profile VARCHAR(50),
  investment_horizon VARCHAR(50),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  PRIMARY KEY (id)
);

-- Create stocks table
CREATE TABLE IF NOT EXISTS stocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(10) UNIQUE NOT NULL,
  name TEXT NOT NULL,
  sector VARCHAR(50),
  industry TEXT,
  market_cap BIGINT,
  pe_ratio FLOAT,
  pb_ratio FLOAT,
  dividend_yield FLOAT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- Create stock_market_data table
CREATE TABLE IF NOT EXISTS stock_market_data (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_id UUID REFERENCES stocks(id),
  date DATE,
  open_price FLOAT,
  high_price FLOAT,
  low_price FLOAT,
  close_price FLOAT,
  volume BIGINT,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE(stock_id, date)
);

-- Create fundamental_metrics table
CREATE TABLE IF NOT EXISTS fundamental_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_id UUID REFERENCES stocks(id),
  revenue_growth FLOAT,
  profit_growth FLOAT,
  roe FLOAT,
  roce FLOAT,
  debt_equity FLOAT,
  interest_coverage FLOAT,
  fcf BIGINT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE(stock_id)
);

-- Create events table
CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  title TEXT NOT NULL,
  description TEXT,
  event_type VARCHAR(50),
  economic_variable VARCHAR(50),
  direction VARCHAR(20),
  magnitude FLOAT,
  confidence FLOAT,
  created_at TIMESTAMP DEFAULT now()
);

-- Create event_analysis table
CREATE TABLE IF NOT EXISTS event_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  event_id UUID REFERENCES events(id),
  event_title TEXT,
  affected_sectors TEXT[],
  opportunity_score FLOAT,
  composite_score FLOAT,
  recommendation VARCHAR(20),
  bull_case TEXT,
  bear_case TEXT,
  risks TEXT[],
  analysis_json JSONB,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- Create stock_scores table
CREATE TABLE IF NOT EXISTS stock_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_analysis_id UUID REFERENCES event_analysis(id),
  stock_id UUID REFERENCES stocks(id),
  stock_symbol VARCHAR(10),
  event_impact_score FLOAT,
  fundamental_score FLOAT,
  valuation_score FLOAT,
  technical_score FLOAT,
  risk_score FLOAT,
  opportunity_score FLOAT,
  recommendation VARCHAR(20),
  confidence FLOAT,
  created_at TIMESTAMP DEFAULT now()
);

-- Create watchlists table
CREATE TABLE IF NOT EXISTS watchlists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  stock_id UUID REFERENCES stocks(id),
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE(user_id, stock_id)
);

-- Create saved_analyses table
CREATE TABLE IF NOT EXISTS saved_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  event_analysis_id UUID REFERENCES event_analysis(id),
  title TEXT,
  is_favorite BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_analyses ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
DROP POLICY IF EXISTS "Users can only view their own profile" ON profiles;
CREATE POLICY "Users can only view their own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can only view their own events" ON events;
CREATE POLICY "Users can only view their own events" ON events
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can only view their own analyses" ON event_analysis;
CREATE POLICY "Users can only view their own analyses" ON event_analysis
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can only view their own watchlists" ON watchlists;
CREATE POLICY "Users can only view their own watchlists" ON watchlists
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can only view their own saved analyses" ON saved_analyses;
CREATE POLICY "Users can only view their own saved analyses" ON saved_analyses
  FOR SELECT USING (auth.uid() = user_id);

-- Create indexes
CREATE INDEX idx_events_user ON events(user_id);
CREATE INDEX idx_event_analysis_user ON event_analysis(user_id);
CREATE INDEX idx_stock_scores_analysis ON stock_scores(event_analysis_id);
CREATE INDEX idx_watchlists_user ON watchlists(user_id);
CREATE INDEX idx_saved_analyses_user ON saved_analyses(user_id);

-- ─────────────────────────────────────────────────────────────────────────
-- 002_historical_events.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Historical Event Engine: reference events + measured market reactions
-- Lets the platform say "in N similar past events, NIFTY/sector/stock moved X% on average"
-- instead of an LLM guessing at a return figure (see spec section 11 and 19).

CREATE TABLE IF NOT EXISTS historical_event_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type VARCHAR(50) NOT NULL,
  economic_variable VARCHAR(50) NOT NULL,
  direction VARCHAR(20) NOT NULL,
  event_label TEXT NOT NULL,
  event_date DATE,
  sector VARCHAR(50),
  nifty_return_1d FLOAT,
  nifty_return_3d FLOAT,
  nifty_return_5d FLOAT,
  nifty_return_20d FLOAT,
  sector_return_1d FLOAT,
  sector_return_3d FLOAT,
  sector_return_5d FLOAT,
  sector_return_20d FLOAT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX idx_historical_event_type ON historical_event_reactions(event_type, economic_variable, direction);

ALTER TABLE historical_event_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Historical reactions are readable by any authenticated user" ON historical_event_reactions;
CREATE POLICY "Historical reactions are readable by any authenticated user" ON historical_event_reactions
  FOR SELECT USING (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────────
-- 003_analysis_extensions.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Session 2 extensions: transmission explanation, counter-argument fields,
-- and risk classification on stock scores.

ALTER TABLE events ADD COLUMN IF NOT EXISTS transmission_explanation TEXT;
ALTER TABLE event_analysis ADD COLUMN IF NOT EXISTS contradictory_evidence TEXT;
ALTER TABLE event_analysis ADD COLUMN IF NOT EXISTS historical_summary JSONB;
ALTER TABLE stock_scores ADD COLUMN IF NOT EXISTS risk_level VARCHAR(20);
ALTER TABLE stock_scores ADD COLUMN IF NOT EXISTS event_impact_direction VARCHAR(20);

-- ─────────────────────────────────────────────────────────────────────────
-- 004_write_policies_and_profile_trigger.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Session 3: fix a real gap from migration 001 — only SELECT policies existed,
-- meaning every INSERT/UPDATE/DELETE from the app (via the anon-key + user
-- session client, which respects RLS) was being silently rejected once RLS
-- actually started enforcing on a populated project. Adds the missing write
-- policies, tightens stock_scores (previously had no RLS at all), and
-- replaces the removed client-side "insert a profile row" step with the
-- standard Supabase trigger pattern so every signup reliably gets a profile.

-- ── profiles: allow the owner to update their own row, and auto-create ──
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    new.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── events: owner can insert their own events ──
DROP POLICY IF EXISTS "Users can insert their own events" ON events;
CREATE POLICY "Users can insert their own events" ON events
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ── event_analysis: owner can insert/update their own analyses ──
DROP POLICY IF EXISTS "Users can insert their own analyses" ON event_analysis;
CREATE POLICY "Users can insert their own analyses" ON event_analysis
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update their own analyses" ON event_analysis;
CREATE POLICY "Users can update their own analyses" ON event_analysis
  FOR UPDATE USING (auth.uid() = user_id);

-- ── watchlists: owner can insert/delete their own entries ──
DROP POLICY IF EXISTS "Users can insert their own watchlist entries" ON watchlists;
CREATE POLICY "Users can insert their own watchlist entries" ON watchlists
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete their own watchlist entries" ON watchlists;
CREATE POLICY "Users can delete their own watchlist entries" ON watchlists
  FOR DELETE USING (auth.uid() = user_id);

-- ── saved_analyses: owner can insert/update/delete their own saves ──
DROP POLICY IF EXISTS "Users can insert their own saved analyses" ON saved_analyses;
CREATE POLICY "Users can insert their own saved analyses" ON saved_analyses
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update their own saved analyses" ON saved_analyses;
CREATE POLICY "Users can update their own saved analyses" ON saved_analyses
  FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete their own saved analyses" ON saved_analyses;
CREATE POLICY "Users can delete their own saved analyses" ON saved_analyses
  FOR DELETE USING (auth.uid() = user_id);

-- ── stock_scores: previously had NO row level security at all. Scope it to
-- the parent event_analysis's owner via subquery, since stock_scores has no
-- user_id column of its own. ──
ALTER TABLE stock_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view scores for their own analyses" ON stock_scores;
CREATE POLICY "Users can view scores for their own analyses" ON stock_scores
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM event_analysis
      WHERE event_analysis.id = stock_scores.event_analysis_id
      AND event_analysis.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can insert scores for their own analyses" ON stock_scores;
CREATE POLICY "Users can insert scores for their own analyses" ON stock_scores
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM event_analysis
      WHERE event_analysis.id = stock_scores.event_analysis_id
      AND event_analysis.user_id = auth.uid()
    )
  );

-- ── stocks: read-only reference data, open to any authenticated user ──
ALTER TABLE stocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated users can read the stock universe" ON stocks;
CREATE POLICY "Authenticated users can read the stock universe" ON stocks
  FOR SELECT USING (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────────
-- 005_news_feed.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Session 4: Live News Discovery
-- News is system-populated shared data, not user-owned, so regular users can
-- read it (RLS SELECT) but cannot write to it directly — only the server,
-- using the service-role client (which bypasses RLS entirely), populates it.

CREATE TABLE IF NOT EXISTS news_feeds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  url TEXT,
  source TEXT,
  image_url TEXT,
  published_at TIMESTAMP,
  fetched_at TIMESTAMP DEFAULT now(),
  content TEXT,
  event_type VARCHAR(50),
  detected_sectors TEXT[],
  relevance_score FLOAT,
  source_hash VARCHAR(64) UNIQUE,
  created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_published ON news_feeds(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_relevance ON news_feeds(relevance_score DESC);

ALTER TABLE news_feeds ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read news" ON news_feeds;
CREATE POLICY "Authenticated users can read news" ON news_feeds
  FOR SELECT USING (auth.role() = 'authenticated');

-- No INSERT/UPDATE/DELETE policy for regular users on purpose — the fetch
-- endpoint writes via the service-role client, which bypasses RLS.

-- ─────────────────────────────────────────────────────────────────────────
-- 006_markets_and_portfolio.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Session 6 (revised): paper portfolio simulation.
--
-- This migration originally also created a `market_snapshots` table that a
-- manual "Refresh Markets" button wrote into. That's gone: indices,
-- commodities, FX and crypto are now fetched live from keyless public feeds
-- on every request (lib/market/yahooFinance.ts + lib/market/cryptoProvider.ts,
-- served by /api/market/live and /api/market/crypto and cached at the edge).
-- Nothing reads a cached market table any more, so it isn't created here.
--
-- If you ran an earlier copy of this file, the leftover table is harmless and
-- can be dropped at your convenience:
--   DROP TABLE IF EXISTS market_snapshots;

-- ── portfolio_positions: user-owned hypothetical "what if I bought" ──
-- positions, following the exact ownership + write-policy pattern watchlists
-- and saved_analyses already use (migration 001 for SELECT, 004 for writes).
CREATE TABLE IF NOT EXISTS portfolio_positions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  stock_scores_id UUID REFERENCES stock_scores(id),
  event_analysis_id UUID REFERENCES event_analysis(id),
  stock_id UUID REFERENCES stocks(id),
  symbol VARCHAR(10) NOT NULL,
  recommendation VARCHAR(20),
  entry_price FLOAT NOT NULL,
  entry_date TIMESTAMP DEFAULT now(),
  simulated_current_price FLOAT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_portfolio_positions_user ON portfolio_positions(user_id);

ALTER TABLE portfolio_positions ENABLE ROW LEVEL SECURITY;

-- DROP-then-CREATE so this file can be re-run safely; CREATE POLICY has no
-- IF NOT EXISTS form, and a half-applied migration is the usual reason
-- someone runs it twice.
DROP POLICY IF EXISTS "Users can view their own portfolio positions" ON portfolio_positions;
CREATE POLICY "Users can view their own portfolio positions" ON portfolio_positions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own portfolio positions" ON portfolio_positions;
CREATE POLICY "Users can insert their own portfolio positions" ON portfolio_positions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own portfolio positions" ON portfolio_positions;
CREATE POLICY "Users can delete their own portfolio positions" ON portfolio_positions
  FOR DELETE USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────────────────
-- 007_seed_stock_universe.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Seeds the stock universe.
--
-- Generated by scripts/build-schema.mjs from lib/market/indianEquities.ts.
-- Do not edit by hand — change the universe and regenerate.
--
-- Without these rows the table exists but is empty, and everything keyed
-- on a stock's database id quietly stops working: an analysis cannot link
-- its scores to a row, so the Watch button has no stock_id to send and
-- fails silently, and the watchlist stays empty however often it is
-- pressed. Re-runnable: conflicts update the name and sector.

INSERT INTO stocks (symbol, name, sector) VALUES
  ('HDFCBANK', 'HDFC Bank', 'Banking'),
  ('ICICIBANK', 'ICICI Bank', 'Banking'),
  ('SBIN', 'State Bank of India', 'Banking'),
  ('KOTAKBANK', 'Kotak Mahindra Bank', 'Banking'),
  ('AXISBANK', 'Axis Bank', 'Banking'),
  ('INDUSINDBK', 'IndusInd Bank', 'Banking'),
  ('BAJFINANCE', 'Bajaj Finance', 'Financials'),
  ('BAJAJFINSV', 'Bajaj Finserv', 'Financials'),
  ('SBILIFE', 'SBI Life Insurance', 'Financials'),
  ('HDFCLIFE', 'HDFC Life Insurance', 'Financials'),
  ('SHRIRAMFIN', 'Shriram Finance', 'Financials'),
  ('JIOFIN', 'Jio Financial Services', 'Financials'),
  ('TCS', 'Tata Consultancy Services', 'IT'),
  ('INFY', 'Infosys', 'IT'),
  ('HCLTECH', 'HCL Technologies', 'IT'),
  ('WIPRO', 'Wipro', 'IT'),
  ('TECHM', 'Tech Mahindra', 'IT'),
  ('LTIM', 'LTIMindtree', 'IT'),
  ('RELIANCE', 'Reliance Industries', 'Energy'),
  ('ONGC', 'Oil & Natural Gas Corporation', 'Energy'),
  ('BPCL', 'Bharat Petroleum', 'Energy'),
  ('COALINDIA', 'Coal India', 'Energy'),
  ('NTPC', 'NTPC', 'Utilities'),
  ('POWERGRID', 'Power Grid Corporation', 'Utilities'),
  ('MARUTI', 'Maruti Suzuki India', 'Auto'),
  ('M&M', 'Mahindra & Mahindra', 'Auto'),
  ('TATAMOTORS', 'Tata Motors', 'Auto'),
  ('BAJAJ-AUTO', 'Bajaj Auto', 'Auto'),
  ('EICHERMOT', 'Eicher Motors', 'Auto'),
  ('HEROMOTOCO', 'Hero MotoCorp', 'Auto'),
  ('HINDUNILVR', 'Hindustan Unilever', 'FMCG'),
  ('ITC', 'ITC', 'FMCG'),
  ('NESTLEIND', 'Nestle India', 'FMCG'),
  ('BRITANNIA', 'Britannia Industries', 'FMCG'),
  ('TATACONSUM', 'Tata Consumer Products', 'FMCG'),
  ('ASIANPAINT', 'Asian Paints', 'Consumer'),
  ('TITAN', 'Titan Company', 'Consumer'),
  ('TRENT', 'Trent', 'Retail'),
  ('SUNPHARMA', 'Sun Pharmaceutical', 'Pharma'),
  ('CIPLA', 'Cipla', 'Pharma'),
  ('DRREDDY', 'Dr. Reddy''s Laboratories', 'Pharma'),
  ('APOLLOHOSP', 'Apollo Hospitals', 'Pharma'),
  ('TATASTEEL', 'Tata Steel', 'Metals'),
  ('JSWSTEEL', 'JSW Steel', 'Metals'),
  ('HINDALCO', 'Hindalco Industries', 'Metals'),
  ('ULTRACEMCO', 'UltraTech Cement', 'Cement'),
  ('GRASIM', 'Grasim Industries', 'Chemicals'),
  ('LT', 'Larsen & Toubro', 'Engineering'),
  ('BEL', 'Bharat Electronics', 'Engineering'),
  ('ADANIENT', 'Adani Enterprises', 'Diversified'),
  ('ADANIPORTS', 'Adani Ports & SEZ', 'Ports'),
  ('BHARTIARTL', 'Bharti Airtel', 'Telecom')
ON CONFLICT (symbol) DO UPDATE
  SET name = EXCLUDED.name,
      sector = EXCLUDED.sector,
      updated_at = now();

