-- Seeds the stock universe.
--
-- Generated by scripts/build-schema.mjs from lib/market/indianEquities.ts.
-- Do not edit by hand — change the universe and regenerate.
--
-- Without these rows the table exists but is empty, and everything keyed
-- on a stock's database id quietly stops working: an analysis cannot link
-- its scores to a row, so the Watch button has no stock_id to send and
-- fails silently, and the watchlist stays empty however often it is
-- pressed. Re-runnable: conflicts update the name and sector.

INSERT INTO stocks (symbol, name, sector) VALUES
  ('HDFCBANK', 'HDFC Bank', 'Banking'),
  ('ICICIBANK', 'ICICI Bank', 'Banking'),
  ('SBIN', 'State Bank of India', 'Banking'),
  ('KOTAKBANK', 'Kotak Mahindra Bank', 'Banking'),
  ('AXISBANK', 'Axis Bank', 'Banking'),
  ('INDUSINDBK', 'IndusInd Bank', 'Banking'),
  ('BAJFINANCE', 'Bajaj Finance', 'Financials'),
  ('BAJAJFINSV', 'Bajaj Finserv', 'Financials'),
  ('SBILIFE', 'SBI Life Insurance', 'Financials'),
  ('HDFCLIFE', 'HDFC Life Insurance', 'Financials'),
  ('SHRIRAMFIN', 'Shriram Finance', 'Financials'),
  ('JIOFIN', 'Jio Financial Services', 'Financials'),
  ('TCS', 'Tata Consultancy Services', 'IT'),
  ('INFY', 'Infosys', 'IT'),
  ('HCLTECH', 'HCL Technologies', 'IT'),
  ('WIPRO', 'Wipro', 'IT'),
  ('TECHM', 'Tech Mahindra', 'IT'),
  ('LTIM', 'LTIMindtree', 'IT'),
  ('RELIANCE', 'Reliance Industries', 'Energy'),
  ('ONGC', 'Oil & Natural Gas Corporation', 'Energy'),
  ('BPCL', 'Bharat Petroleum', 'Energy'),
  ('COALINDIA', 'Coal India', 'Energy'),
  ('NTPC', 'NTPC', 'Utilities'),
  ('POWERGRID', 'Power Grid Corporation', 'Utilities'),
  ('MARUTI', 'Maruti Suzuki India', 'Auto'),
  ('M&M', 'Mahindra & Mahindra', 'Auto'),
  ('TATAMOTORS', 'Tata Motors', 'Auto'),
  ('BAJAJ-AUTO', 'Bajaj Auto', 'Auto'),
  ('EICHERMOT', 'Eicher Motors', 'Auto'),
  ('HEROMOTOCO', 'Hero MotoCorp', 'Auto'),
  ('HINDUNILVR', 'Hindustan Unilever', 'FMCG'),
  ('ITC', 'ITC', 'FMCG'),
  ('NESTLEIND', 'Nestle India', 'FMCG'),
  ('BRITANNIA', 'Britannia Industries', 'FMCG'),
  ('TATACONSUM', 'Tata Consumer Products', 'FMCG'),
  ('ASIANPAINT', 'Asian Paints', 'Consumer'),
  ('TITAN', 'Titan Company', 'Consumer'),
  ('TRENT', 'Trent', 'Retail'),
  ('SUNPHARMA', 'Sun Pharmaceutical', 'Pharma'),
  ('CIPLA', 'Cipla', 'Pharma'),
  ('DRREDDY', 'Dr. Reddy''s Laboratories', 'Pharma'),
  ('APOLLOHOSP', 'Apollo Hospitals', 'Pharma'),
  ('TATASTEEL', 'Tata Steel', 'Metals'),
  ('JSWSTEEL', 'JSW Steel', 'Metals'),
  ('HINDALCO', 'Hindalco Industries', 'Metals'),
  ('ULTRACEMCO', 'UltraTech Cement', 'Cement'),
  ('GRASIM', 'Grasim Industries', 'Chemicals'),
  ('LT', 'Larsen & Toubro', 'Engineering'),
  ('BEL', 'Bharat Electronics', 'Engineering'),
  ('ADANIENT', 'Adani Enterprises', 'Diversified'),
  ('ADANIPORTS', 'Adani Ports & SEZ', 'Ports'),
  ('BHARTIARTL', 'Bharti Airtel', 'Telecom')
ON CONFLICT (symbol) DO UPDATE
  SET name = EXCLUDED.name,
      sector = EXCLUDED.sector,
      updated_at = now();
