/**
 * Concatenates the numbered migrations into one re-runnable file.
 *
 *   node scripts/build-schema.mjs
 *
 * Why: setting the project up meant pasting six files into the Supabase SQL
 * editor in the right order, and missing one left a table the app queries but
 * the database does not have — which is how /portfolio ended up failing for
 * signed-in users. One file, safe to run twice, removes that whole class of
 * setup mistake.
 *
 * The only transform is on policies: CREATE POLICY has no IF NOT EXISTS, so
 * each one is preceded by a DROP POLICY IF EXISTS. Everything else in the
 * migrations is already guarded.
 */
import { execSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

const DIR = 'database/migrations'
const OUT = 'database/schema.sql'

function writeSeedMigration() {
  // ── Seed the stocks table from the equity universe ────────────────────────
  //
  // Without this the table is created empty, and everything keyed on a stock's
  // database id quietly stops working: the analysis cannot link its scores to a
  // row, so the Watch button has no stock_id to insert and fails silently, and
  // the watchlist page stays empty however many times you press it. Generating
  // the seed from lib/market/indianEquities.ts rather than hand-writing it
  // keeps the universe and the table from drifting apart.
  const tmp = mkdtempSync(path.join(process.cwd(), '.tsbuild-schema-'))
  try {
    const tsconfig = path.join(tmp, 'tsconfig.json')
    writeFileSync(
      tsconfig,
      JSON.stringify({
        compilerOptions: {
          target: 'es2022',
          module: 'commonjs',
          moduleResolution: 'node',
          skipLibCheck: true,
          outDir: tmp,
          rootDir: path.join(process.cwd(), 'lib'),
          types: [],
        },
        files: [path.join(process.cwd(), 'lib/market/indianEquities.ts')],
      })
    )
    try {
      execSync(`./node_modules/.bin/tsc --project ${tsconfig}`, { stdio: 'pipe' })
    } catch (err) {
      if (!existsSync(path.join(tmp, 'market/indianEquities.js'))) throw err
    }
    const require = createRequire(import.meta.url)
    const { NIFTY_50 } = require(path.join(tmp, 'market/indianEquities.js'))
    const esc = (v) => String(v).replace(/'/g, "''")

    const seed = [
      `-- Seeds the stock universe.`,
      `--`,
      `-- Generated by scripts/build-schema.mjs from lib/market/indianEquities.ts.`,
      `-- Do not edit by hand — change the universe and regenerate.`,
      `--`,
      `-- Without these rows the table exists but is empty, and everything keyed`,
      `-- on a stock's database id quietly stops working: an analysis cannot link`,
      `-- its scores to a row, so the Watch button has no stock_id to send and`,
      `-- fails silently, and the watchlist stays empty however often it is`,
      `-- pressed. Re-runnable: conflicts update the name and sector.`,
      ``,
      `INSERT INTO stocks (symbol, name, sector) VALUES`,
      NIFTY_50.map((s) => `  ('${esc(s.symbol)}', '${esc(s.name)}', '${esc(s.sector)}')`).join(',\n'),
      `ON CONFLICT (symbol) DO UPDATE`,
      `  SET name = EXCLUDED.name,`,
      `      sector = EXCLUDED.sector,`,
      `      updated_at = now();`,
      ``,
    ].join('\n')
    writeFileSync(path.join(DIR, SEED_MIGRATION), seed)
    console.log(`${DIR}/${SEED_MIGRATION}: ${NIFTY_50.length} stocks`)
  } finally {
    rmSync(tmp, { recursive: true, force: true })
  }
}

const SEED_MIGRATION = '007_seed_stock_universe.sql'

writeSeedMigration()

const files = readdirSync(DIR)
  .filter((f) => /^\d+_.*\.sql$/.test(f))
  .sort()

const parts = [
  `-- PULSE — complete database schema`,
  `--`,
  `-- Generated by scripts/build-schema.mjs from ${DIR}. Do not edit by hand:`,
  `-- edit the numbered migration and regenerate, so both stay in step.`,
  `--`,
  `-- Paste the whole file into the Supabase SQL editor and run it once.`,
  `-- It is safe to run again — every statement is guarded.`,
  ``,
]

for (const file of files) {
  const raw = readFileSync(path.join(DIR, file), 'utf8')

  // Give every policy a DROP in front of it, unless the migration already did.
  const guarded = raw.replace(
    /^CREATE POLICY ("(?:[^"]+)") ON (\w+)/gm,
    (match, name, table) => `DROP POLICY IF EXISTS ${name} ON ${table};\n${match}`
  )
  // …then collapse any double-DROP introduced where one was already present.
  const deduped = guarded.replace(
    /^(DROP POLICY IF EXISTS "[^"]+" ON \w+;)\n\1$/gm,
    '$1'
  )

  parts.push(
    `-- ─────────────────────────────────────────────────────────────────────────`,
    `-- ${file}`,
    `-- ─────────────────────────────────────────────────────────────────────────`,
    ``,
    deduped.trim(),
    ``,
  )
}

writeFileSync(OUT, parts.join('\n') + '\n')
console.log(`${OUT}: ${files.length} migrations, ${parts.join('\n').split('\n').length} lines`)
